In [1]:
#import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.ensemble import RandomForestRegressor

In [2]:
dataset = pd.read_csv('train.csv')
dataset.shape

(630000, 13)

In [3]:
dataset.head()

,id,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,0,21,female,b.sc,7.91,98.8,no,4.9,average,online videos,low,easy,78.3
1,1,18,other,diploma,4.95,94.8,yes,4.7,poor,self-study,medium,moderate,46.7
2,2,20,female,b.sc,4.68,92.6,yes,5.8,poor,coaching,high,moderate,99.0
3,3,19,male,b.sc,2.00,49.5,yes,8.3,average,group study,high,moderate,63.9
4,4,23,male,bca,7.65,86.9,yes,9.6,good,self-study,high,easy,100.0

In [4]:
dataset.isnull().sum()

id                  0
age                 0
gender              0
course              0
study_hours         0
class_attendance    0
internet_access     0
sleep_hours         0
sleep_quality       0
study_method        0
facility_rating     0
exam_difficulty     0
exam_score          0
dtype: int64

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                630000 non-null  int64
 1   age               630000 non-null  int64
 2   gender            630000 non-null  object
 3   course            630000 non-null  object
 4   study_hours       630000 non-null  float64
 5   class_attendance  630000 non-null  float64
 6   internet_access   630000 non-null  object
 7   sleep_hours       630000 non-null  float64
 8   sleep_quality     630000 non-null  object
 9   study_method      630000 non-null  object
 10  facility_rating   630000 non-null  object
 11  exam_difficulty   630000 non-null  object
 12  exam_score        630000 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 62.5+ MB

In [6]:
#dropping non needed columns
dataset.drop(['id'],axis=1,inplace=True)

In [7]:
dataset.head()

,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,21,female,b.sc,7.91,98.8,no,4.9,average,online videos,low,easy,78.3
1,18,other,diploma,4.95,94.8,yes,4.7,poor,self-study,medium,moderate,46.7
2,20,female,b.sc,4.68,92.6,yes,5.8,poor,coaching,high,moderate,99.0
3,19,male,b.sc,2.00,49.5,yes,8.3,average,group study,high,moderate,63.9
4,23,male,bca,7.65,86.9,yes,9.6,good,self-study,high,easy,100.0

In [8]:
#finding the unique elements in the dataset
dataset['gender'].unique()

array(['female', 'other', 'male'], dtype=object)

In [9]:
dataset['course'].value_counts()

course
b.tech     131236
b.sc       111554
b.com      110932
bca         88721
bba         75644
ba          61989
diploma     49924
Name: count, dtype: int64

In [10]:
dataset['internet_access'].value_counts()

internet_access
yes    579423
no      50577
Name: count, dtype: int64

In [11]:
dataset['study_method'].value_counts()

study_method
coaching         131697
self-study       131131
mixed            123086
group study      123009
online videos    121077
Name: count, dtype: int64

In [12]:
dataset['sleep_quality'].value_counts()

sleep_quality
poor       213675
good       213089
average    203236
Name: count, dtype: int64

In [13]:
dataset['facility_rating'].value_counts()

facility_rating
medium    214082
low       212378
high      203540
Name: count, dtype: int64

In [14]:
dataset['exam_difficulty'].value_counts()

exam_difficulty
moderate    353982
easy        176540
hard         99478
Name: count, dtype: int64

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   age               630000 non-null  int64
 1   gender            630000 non-null  object
 2   course            630000 non-null  object
 3   study_hours       630000 non-null  float64
 4   class_attendance  630000 non-null  float64
 5   internet_access   630000 non-null  object
 6   sleep_hours       630000 non-null  float64
 7   sleep_quality     630000 non-null  object
 8   study_method      630000 non-null  object
 9   facility_rating   630000 non-null  object
 10  exam_difficulty   630000 non-null  object
 11  exam_score        630000 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 57.7+ MB

In [16]:
# label encoding for the columns
le = LabelEncoder()
dataset['gender'] = le.fit_transform(dataset['gender'])
dataset['course'] = le.fit_transform(dataset['course'])
dataset['internet_access'] = le.fit_transform(dataset['internet_access'])
dataset['study_method'] = le.fit_transform(dataset['study_method'])
dataset['sleep_quality'] = le.fit_transform(dataset['sleep_quality'])

#ordinal encoding for facility_rating and exam_difficulty
dataset['facility_rating'] = dataset['facility_rating'].map({ 'high': 3, 'medium': 2, 'low': 1})
dataset['exam_difficulty'] = dataset['exam_difficulty'].map({ 'hard': 3, 'moderate': 2, 'easy': 1})

In [17]:
dataset.head()

,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
0,21,0,1,7.91,98.8,0,4.9,0,3,1,1,78.3
1,18,2,6,4.95,94.8,1,4.7,2,4,2,2,46.7
2,20,0,1,4.68,92.6,1,5.8,2,0,3,2,99.0
3,19,1,1,2.00,49.5,1,8.3,0,1,3,2,63.9
4,23,1,5,7.65,86.9,1,9.6,1,4,3,1,100.0

In [18]:
dataset['exam_difficulty'].value_counts()

exam_difficulty
2    353982
1    176540
3     99478
Name: count, dtype: int64

In [19]:
dataset.describe()

,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty,exam_score
count,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.00000,630000.000000,630000.000000,630000.000000,630000.000000
mean,20.545821,1.004424,2.548759,4.002337,71.987261,0.919719,7.072758,1.01657,1.995137,1.985971,1.877679,62.506672
std,2.260238,0.815909,1.922056,2.359880,17.430098,0.271728,1.744811,0.81332,1.433934,0.812399,0.650509,18.916884
min,17.000000,0.000000,0.000000,0.080000,40.600000,0.000000,4.100000,0.00000,0.000000,1.000000,1.000000,19.599000
25%,19.000000,0.000000,1.000000,1.970000,57.000000,1.000000,5.600000,0.00000,1.000000,1.000000,1.000000,48.800000
50%,21.000000,1.000000,2.000000,4.000000,72.600000,1.000000,7.100000,1.00000,2.000000,2.000000,2.000000,62.600000
75%,23.000000,2.000000,4.000000,6.050000,87.200000,1.000000,8.600000,2.00000,3.000000,3.000000,2.000000,76.300000
max,24.000000,2.000000,6.000000,7.910000,99.400000,1.000000,9.900000,2.00000,4.000000,3.000000,3.000000,100.000000

In [20]:
#training dataset
X = dataset.drop(['exam_score'],axis=1)
y = dataset['exam_score']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [21]:
m1 = LinearRegression()
m1.fit(X_train,y_train)
pred1 = m1.predict(X_test)
print(r2_score(y_test,pred1))

0.7414171245068428

In [22]:
root_mean_squared_error(y_test,pred1)

9.589800006241983

In [23]:
m2 = RandomForestRegressor(max_depth=50)
m2.fit(X_train,y_train)
pred2 = m2.predict(X_test)
print(r2_score(y_test,pred2))

0.7663703199286116

In [24]:
root_mean_squared_error(y_test,pred2)

9.11535688738943

In [25]:
pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.1.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.27.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

**Reasoning**:
Now that `xgboost` is installed, I need to import `XGBRegressor`, initialize a model, train it using the training data (`X_train` and `y_train`), make predictions on the test set (`X_test`), and then calculate the Root Mean Squared Error (RMSE) to evaluate the model as specified in the subtask.

In [26]:
import xgboost
from xgboost import XGBRegressor

m5 = XGBRegressor()
m5.fit(X_train, y_train)
pred5 = m5.predict(X_test)

rmse_xgboost = root_mean_squared_error(y_test, pred5)
print(f"XGBoost RMSE: {rmse_xgboost}")

XGBoost RMSE: 8.804512193311822

In [31]:
#use test.csv to get sample_submission type like csv file
test = pd.read_csv('test.csv')
test.shape

(270000, 12)

In [36]:
test_dataset = pd.read_csv('test.csv')
test_ids = test_dataset['id']
test_dataset.drop(['id'], axis=1, inplace=True)

In [37]:
# Define the unique categories for each column based on the training data's original values,
# sorted alphabetically, which is how LabelEncoder assigns integers.

gender_categories = ['female', 'male', 'other']
course_categories = ['ba', 'b.com', 'b.sc', 'b.tech', 'bba', 'bca', 'diploma']
internet_access_categories = ['no', 'yes']
sleep_quality_categories = ['average', 'good', 'poor']
study_method_categories = ['coaching', 'group study', 'mixed', 'online videos', 'self-study']

In [38]:
le_gender = LabelEncoder()
le_gender.fit(gender_categories)

le_course = LabelEncoder()
le_course.fit(course_categories)

le_internet_access = LabelEncoder()
le_internet_access.fit(internet_access_categories)

le_study_method = LabelEncoder()
le_study_method.fit(study_method_categories)

le_sleep_quality = LabelEncoder()
le_sleep_quality.fit(sleep_quality_categories)

LabelEncoder()

In [39]:
# Transform the test_dataset columns using the fitted LabelEncoders
test_dataset['gender'] = le_gender.transform(test_dataset['gender'])
test_dataset['course'] = le_course.transform(test_dataset['course'])
test_dataset['internet_access'] = le_internet_access.transform(test_dataset['internet_access'])
test_dataset['study_method'] = le_study_method.transform(test_dataset['study_method'])
test_dataset['sleep_quality'] = le_sleep_quality.transform(test_dataset['sleep_quality'])

In [40]:
test_dataset['facility_rating'] = test_dataset['facility_rating'].map({ 'high': 3, 'medium': 2, 'low': 1})
test_dataset['exam_difficulty'] = test_dataset['exam_difficulty'].map({ 'hard': 3, 'moderate': 2, 'easy': 1})

test_dataset.head()

,age,gender,course,study_hours,class_attendance,internet_access,sleep_hours,sleep_quality,study_method,facility_rating,exam_difficulty
0,24,2,3,6.85,65.2,1,5.2,2,1,3,1
1,18,1,6,6.61,45.0,0,9.3,2,0,1,1
2,24,0,2,6.60,98.5,1,6.2,1,1,2,2
3,24,1,6,3.03,66.3,1,5.7,0,2,2,2
4,20,0,2,2.03,42.4,1,9.2,0,0,1,2

In [41]:
predictions = m5.predict(test_dataset)

submission_df = pd.DataFrame({'id': test_ids, 'exam_score': predictions})
submission_df.to_csv('submission.csv', index=False)

print("Submission file created successfully!")
print(submission_df.head())

Submission file created successfully!
       id  exam_score
0  630000   69.499405
1  630001   70.021828
2  630002   89.353264
3  630003   54.417511
4  630004   46.736572